const html = {
    
    errorDiv: document.getElementById('errorDiv'),
    home: document.getElementById('home'),
    hourlyDiv: document.getElementById('hourlyDiv'),
    weeklyDiv: document.getElementById('weeklyDiv'),
    weekly: document.getElementById('weekly'),
    aboutDiv: document.getElementById('aboutDiv'),
    hourly: document.getElementById('hourly'),
    tBodyHourly: document.getElementById('tBodyHourly'),
    tBodyWeekly: document.getElementById('tBodyWeekly'),
    tempTableHeader: document.getElementById('tempTableHeader'),
    weeklyMax: document.getElementById('weeklyMax'),
    weeklyMin: document.getElementById('weeklyMin'),
    weeklyAvg: document.getElementById('weeklyAvg'),
    about: document.getElementById('about'),
    searchBar: document.getElementById('searchBar'),
    searchBtn: document.getElementById('searchBtn'),
    homeDiv: document.getElementById('homeDiv'),
    homeDivWithData: document.getElementById('homeDivWithData'),
    cityName: document.getElementById('cityName'),
    currentTemp: document.getElementById('currentTemp'),
    feelsLike: document.getElementById('feelsLike'),
    msg: document.getElementById('msg'),
    weatherStatus: document.getElementById('weatherStatus'),
    weatherImg: document.getElementById('weatherImg'),
    maxTemp: document.getElementById('maxTemp'),
    maxHumd: document.getElementById('maxHumd'),
    avgTemp: document.getElementById('avgTemp'),
    avgHumd: document.getElementById('avgHumd'),
    lowTemp: document.getElementById('lowTemp'),
    lowHumd: document.getElementById('lowHumd'),
    warmestDay: document.getElementById('warmestDay'),
    coldestDay: document.getElementById('coldestDay'),
};

export {html};